name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-format:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install tools (SwiftLint & SwiftFormat)
        run: |
          brew update
          brew install swiftlint swiftformat

      - name: SwiftFormat (lint mode)
        run: swiftformat --lint .

      - name: SwiftLint
        run: swiftlint

  build-test:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        scheme: [CommerceKitCore, CommerceKitAI, CommerceKitUI]

    steps:
      - uses: actions/checkout@v4

      # 1) Chọn đúng Xcode (an toàn hơn so với xcode-select thủ công)
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'   # hoặc '15.*' nếu bạn muốn tự động minor

      # 2) In phiên bản để debug khi cần
      - name: Xcode version
        run: |
          xcodebuild -version
          xcode-select -p

      # 3) Cache SwiftPM để build nhanh hơn
      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # 4) Bảo đảm có simulator iPhone 15 (tạo nếu thiếu) & dùng OS=latest
      - name: Prepare Simulator
        run: |
          xcrun simctl list devicetypes | grep "iPhone 15" || true
          xcrun simctl list runtimes | grep iOS || true
          # tạo thiết bị tên CI-iPhone-15 nếu chưa có (không fail nếu đã tồn tại)
          xcrun simctl create "CI-iPhone-15" "iPhone 15" "iOS" || true

      # 5) Resolve packages trước khi build (tránh fail do network)
      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -workspace CommerceWorkspace.xcworkspace \
            -scheme ${{ matrix.scheme }}

      # 6) Build & Test + coverage
      - name: Build & Test (+ coverage)
        run: |
          xcodebuild \
            -workspace CommerceWorkspace.xcworkspace \
            -scheme ${{ matrix.scheme }} \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -enableCodeCoverage YES \
            -resultBundlePath ${{ matrix.scheme }}.xcresult \
            test | xcpretty

      # 7) Upload .xcresult để tải về xem chi tiết khi cần
      - name: Upload ${{ matrix.scheme }} xcresult
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.scheme }}-xcresult
          path: ${{ matrix.scheme }}.xcresult
