# Tên workflow hiển thị trên tab Actions
name: CI

# Kích hoạt khi: (1) mở Pull Request, (2) push vào nhánh main
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # ---- Job 1: Kiểm tra format & lint (nhanh) ----
  lint-format:
    runs-on: macos-14   # Runner macOS có sẵn Xcode
    steps:
      - uses: actions/checkout@v4  # Tải code của repo về runner

      # Cài SwiftLint & SwiftFormat (dùng Homebrew trên runner)
      - name: Install tools (SwiftLint & SwiftFormat)
        run: |
          brew update
          brew install swiftlint swiftformat

      # Chạy SwiftFormat ở chế độ lint (chỉ báo lỗi, không sửa)
      - name: SwiftFormat (lint mode)
        run: swiftformat --lint .

      # Chạy SwiftLint để kiểm các rule style
      - name: SwiftLint
        run: swiftlint

  # ---- Job 2: Build + Test (matrix 3 module) ----
  build-test:
    runs-on: macos-14
    strategy:
      fail-fast: false        # 1 module fail vẫn cho 2 module còn lại chạy
      matrix:
        scheme: [CommerceKitCore, CommerceKitAI, CommerceKitUI]  # 3 scheme phải "Shared"
    steps:
      - uses: actions/checkout@v4

      # Chọn phiên bản Xcode cụ thể (đổi nếu runner cập nhật)
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      # Build + Test + bật coverage; lưu .xcresult để tải về xem chi tiết nếu cần
      - name: Build & Test (+ coverage + export .xcresult)
        run: |
          xcodebuild \
            -workspace CommerceWorkspace.xcworkspace \
            -scheme ${{ matrix.scheme }} \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -enableCodeCoverage YES \
            -resultBundlePath ${{ matrix.scheme }}.xcresult \
            test

      # Upload artifact (kết quả test/coverage) để tải về
      - name: Upload ${{ matrix.scheme }} xcresult
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.scheme }}-xcresult
          path: ${{ matrix.scheme }}.xcresult
